Arguments count: 1
Argument      0: ./run-monarch.py
----------------------------------------
10 households, 0 dependent tasks, 10 fully flexible tasks, 0 semi-flexible tasks, 0 fixed tasks, 1 penalty weight. 
----------------------------------------
0. The community is created. 
0. Aggregator is created. 
1. Best step size 0.433, 79 iterations, cost 4108359.49, using minizinc_fw
2. Best step size 0.154, 27 iterations, cost 4104602.21, using minizinc_fw
3. Best step size 0.148, 14 iterations, cost 4102407.86, using minizinc_fw
4. Best step size 0.111, 11 iterations, cost 4101292.36, using minizinc_fw
5. Best step size 0.032, 3 iterations, cost 4101186.14, using minizinc_fw
6. Best step size 0, 0 iterations, cost 4101186.14, using minizinc_fw
Converged in 6
Data are written and graphs are painted. 
0. The community is read. 
0. Aggregator is read. 
1. Best step size 0.445, 95 iterations, cost 4105203.87, using ogsa_fw
2. Best step size 0.137, 20 iterations, cost 4102515.39, using ogsa_fw
3. Best step size 0.115, 15 iterations, cost 4101155.54, using ogsa_fw
4. Best step size 0.026, 3 iterations, cost 4101039.45, using ogsa_fw
5. Best step size 0.002, 1 iterations, cost 4101037.77, using ogsa_fw
6. Best step size 0.001, 1 iterations, cost 4101035.4, using ogsa_fw
7. Best step size 0.001, 1 iterations, cost 4101035.0, using ogsa_fw
8. Best step size 0.011, 2 iterations, cost 4101020.0, using ogsa_fw
9. Best step size 0, 0 iterations, cost 4101020.0, using ogsa_fw
Converged in 9
Data are written and graphs are painted. 
----------------------------------------
Traceback (most recent call last):
  File "/mnt/lustre/projects/td70/py385/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'inconvenient'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./run-monarch.py", line 157, in <module>
    main(new_data=new,
  File "./run-monarch.py", line 119, in main
    df_exp[s_obj] = df_exp[s_penalty] + df_exp[p_cost]
  File "/mnt/lustre/projects/td70/py385/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/mnt/lustre/projects/td70/py385/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'inconvenient'
